# Generated by Django 4.2 on 2023-12-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='newarrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_company', models.CharField(max_length=200)),
                ('new_name', models.CharField(max_length=200)),
                ('new_description', models.TextField()),
                ('new_price', models.IntegerField()),
                ('new_rating', models.IntegerField()),
                ('new_img', models.FileField(default=None, max_length=250, null=True, upload_to='new_images/')),
            ],
        ),
    ]
